ARG FEDORA_VERSION="40"

FROM quay.io/fedora-ostree-desktops/silverblue:${FEDORA_VERSION} AS silverblue

LABEL org.opencontainers.image.title="Silverblue (andyrusiecki)"
LABEL org.opencontainers.image.description="Customized Fedora Silverblue"

COPY base/ /

RUN rpm-ostree install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

RUN rpm-ostree override remove \
  firefox \
  firefox-langpacks \
  toolbox

RUN rpm-ostree install \
  adw-gtk3-theme \
  containerd.io \
  distrobox \
  docker-buildx-plugin \
  docker-ce \
  docker-ce-cli \
  docker-compose-plugin \
  fish \
  gnome-console \
  gnome-tweaks \
  langpacks-en \
  man-pages \
  starship \
  steam-devices \
  tailscale

RUN systemctl enable rpm-ostreed-automatic.timer && \
  systemctl enable flatpak-system-update.timer && \
  systemctl --global enable flatpak-user-update.timer && \
  systemctl enable tailscaled \
  systemctl enable docker

RUN /tmp/install-fonts.sh

RUN rm -rf /tmp/* /var/* && \
  ostree container commit
