ARG FEDORA_VERSION="40"

FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION} AS dev-toolbox

LABEL org.opencontainers.image.title="Dev Toolbox"
LABEL org.opencontainers.image.description="Customized Dev Environment"

COPY base/ /

# Set max dnf parallel downloads to 20
RUN echo "max_parallel_downloads=20" >> /etc/dnf/dnf.conf

# add symlinks to host for podman
RUN ln -s /usr/bin/distrobox-host-exec /usr/local/bin/docker

# install extra packages
RUN dnf install -y --refresh \
  awscli2 \
  fish \
  golang \
  jq \
  kubectl \
  make \
  neovim \
  starship
