ARG FEDORA_VERSION="39"

FROM quay.io/fedora-ostree-desktops/base:${FEDORA_VERSION} AS hyprland

COPY base/ /

# add yq binary (no rpm available)
COPY --from=docker.io/mikefarah/yq /usr/bin/yq /usr/bin/yq

RUN rpm-ostree install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

RUN rpm-ostree install \
  adw-gtk3-theme \
  btop \
  catimg \
  distrobox \
  dunst \
  fish \
  git \
  grim \
  hyprland \
  hyprland-contrib \
  hyprpaper \
  hypridle \
  hyprlock \
  hyprshot \
  imv \
  kanshi \
  kitty \
  mpv \
  neovim \
  playerctl \
  polkit-gnome \
  qt6-qtwayland \
  ranger \
  rofi-wayland \
  sddm \
  slurp \
  starship \
  steam-devices \
  tailscale \
  thunar \
  thunar-archive-plugin \
  thunar-volman \
  waybar \
  wlsunset \
  wl-clipboard \
  xdg-desktop-portal-hyprland

RUN /tmp/install-fonts.sh
#RUN /tmp/install-themes.sh
#RUN /tmp/install-screenshot-tools.sh

RUN systemctl enable sddm && \
  systemctl enable rpm-ostreed-automatic.timer && \
  systemctl enable tailscaled

RUN rm -rf /tmp/* /var/* && \
  ostree container commit
