name: Build and Push Images

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: '0 15 * * 6'

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [
          'malachite-gnome',
          'malachite-gnome-framework',
          'dev-toolbox'
        ]

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      run: 'echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin'

    - name: 'Build and Push Images'
      run: |
        build_date=$(date +%s)
        image_base="ghcr.io/andyrusiecki/${{ matrix.image }}"

        docker build . --file Containerfile --target ${{ matrix.image }} --tag ${image_base}:${build_date}
        docker tag ${image_base}:${build_date} ${image_base}:latest
        docker push --all-tags ${image_base}


